promising_head_relations = {'acl:of', 
'conj:and', 
'advcl:based_on', 
'advcl:while', 
'xcomp', 
'nmod:npmod', 
'nmod:behind', 
'acl:relcl', 
'appos', 
'nmod:under', 
'acl:from', 
'nmod:of', 
'nmod:for', 
'acl', 
'nmod:as_of', 
'dobj', 
'nsubjpass', 
'dep', 
'nmod:after',
'amod', 
'nmod:before', 
'nmod:between', 
'compound', 
'nmod:since', 
'nmod:poss', 
'nmod:through', 
'nmod:within', 
'nmod:from', 
'advcl:followed_by', 
'nsubj', 
'nmod:to', 
'nmod:on', 
'nmod:tmod', 
'nmod:until', 
'nmod:including', 
'nmod:than', 
'nmod:above', 
'root', 
'nmod:at', 
'nmod:during', 
'nmod:as', 
'ccomp', 
'conj:or', 
'advcl:from', 
'nmod:with', 
"nmod:'s", 
'nmod:by', 
'nmod:near', 
'iobj', 
'nummod', 
'conj', 
'nsubj:xsubj', 
'nmod:according_to', 
'advmod', 
'nmod:in', 
'conj:but', 
'advcl:if', 
'nmod:over', 
'advcl:compared_with',
'case',
'advcl:after',
'parataxis',
'det',
'advcl:to',
'nmod:agent',
'acl',
'nmod:compared_with',
'ref'
 }

nominal_head_right_branch_first_order_break_relations = {'acl' , 'acl:relcl' , 'appos' , 'ref' , 'punct' , "nmod:for" , "nmod:in" , "nummod" }
nominal_head_left_branch_first_order_break_relations = { 'nmod:poss' , 'case' , 'nummod' , 'amod'  , 'det'}
nominal_head_left_branch_first_order_break_pos = { 'ADP' }

verbal_head_right_branch_first_order_break_relations = { 'conj:and' , 'advcl:while' , 'advcl:compared_with' , 'dobj' , 'cc' }
verbal_head_left_branch_first_order_break_relations = { 'nsubjpass' , 'nsubj' , 'punct' , 'nmod:of' , 'mark' , 'nmod:in' , 'nmod:in' , 'mwe' }

non_verbal_non_nominal_head_left_branch_first_order_break_relations = { 'case' }  

tag2ctag = {'#':"SYM" ,
    "$" :"SYM",
    "''":"PUNCT",
    ","	:"PUNCT",
    "-LRB-":"PUNCT",
    "-RRB-":"PUNCT",
    ".":"PUNCT",
    ":":"PUNCT",
    "AFX":"ADJ",
    "CC":"CCONJ",
    "CD":"NUM",
    "DT":"DET",
    "EX":"ADV",
    "FW":"X",
    "HYPH":"PUNCT",
    "IN":"ADP",
    "JJ":"ADJ",
    "JJR":"ADJ",
    "JJS":"ADJ",
    "LS":"PUNCT",
    "MD":"VERB",
    "NIL":"X",
    "NN":"NOUN",
    "NNP":"PROPN",
    "NNPS":"PROPN",
    "NNS":"NOUN",
    "PDT":"DET",
    "POS":"PART",
    "PRP":"PRON",
    "PRP$":"DET",
    "RB":"ADV",
    "RBR":"ADV",
    "RBS":"ADV",
    "RP":"PART",
    "SYM":"SYM",
    "TO":"PART",
    "UH":"INTJ",
    "VB":"VERB",
    "VBD":"VERB",
    "VBG":"VERB",
    "VBN":"VERB",
    "VBP":"VERB",
    "VBZ":"VERB",
    "WDT":"DET",
    "WP":"PRON",
    "WP$":"DET",
    "WRB":"ADV",
    "``":"PUNCT"}